### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by coolcode** [Attest/annotations-action#36]
```
##[endgroup***
/home/runner/work/_actions/Attest/annotations-action/v1.0.3/dist/index.js:113
    return navigator.userAgent;
    ^

ReferenceError: navigator is not defined
    at Object.getUserAgent (/home/runner/work/_actions/Attest/annotations-action/v1.0.3/dist/index.js:113:5)
    at /home/runner/work/_actions/Attest/annotations-action/v1.0.3/dist/index.js:480:61
    at createCommonjsModule (/home/runner/work/_actions/Attest/annotations-action/v1.0.3/dist/index.js:60:35)
    at Object.<anonymous> (/home/runner/work/_actions/Attest/annotations-action/v1.0.3/dist/index.js:121:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by thomasaarholt** [comment]
I am also getting this error when running with the example code and the example annotations file.

**Comment by parashagrawal** [comment]
Same error here.
